---
version: '3'
services:
  ark-sa:
    container_name: ark
    image: johnnyknighten/ark-sa-server:latest
    restart: unless-stopped
    environment:
      #- TZ=America/Los_Angeles
      - GAME_PORT=8888
      - QUERY_PORT=27016
      - MAX_PLAYERS=55
      - SERVER_NAME="Containerized Server Test223"
      - SERVER_PASSWORD=
      - ADMIN_PASSWORD=adminpassword25
      - ENABLE_PVE=False
      - SKIP_FILE_VALIDATION=False
      - UPDATE_ON_BOOT=True
      - ENABLE_RCON=True
      - RCON_PORT=27021
      - MOD_LIST="927131, 893657"
      - MULTI_HOME=0.0.0.0      # Make Your Public IP
      - EPIC_PUBLIC_IP=0.0.0.0  # Make Your Public IP
      - NO_BATTLEYE=True
      - REBUILD_CONFIG=True
      - SCHEDULED_RESTART=False
      - BACKUP_ON_SCHEDULED_RESTART=False
      - RESTART_CRON=0 4 * * 0,3
      - SCHEDULED_UPDATE=False
      - UPDATE_CRON=0 5 * * 6
      - BACKUP_ON_STOP=True
      - RETAIN_BACKUPS=10
    volumes:
      - 'ark-server:/ark-server/server'
      - 'ark-backups:/ark-server/backups'
      - 'ark-logs:/ark-server/logs'
    ports:
      - 8888:8888/udp
      - 8889:8889/udp
      - 27016:27016/udp
      - 27021:27021/tcp
volumes:
  ark-server:
  ark-backups:
  ark-logs:
