name: Build and Test
run-name: Build/Test for PR #${{ github.event.number }} on ${{ github.head_ref }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: "Dockerfile"

    - name: Build Docker image (Push To Cache)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: johnnyknighten/ark-sa-server:latest
        cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest
    needs:
      - lint-and-build
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (From Cache)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: johnnyknighten/ark-sa-server:latest
        cache-from: type=gha

    - name: Test wget is installed
      run: |
        docker run --rm \
          --entrypoint wget \
          johnnyknighten/ark-sa-server:latest \
          --version
