name: Build and Test
run-name: Build/Test for PR #${{ github.event.number }} on ${{ github.head_ref }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: "Dockerfile"
        failure-threshold: error

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error
        scandir: './bin'

    - name: Build Docker image (Push To Cache)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: johnnyknighten/ark-sa-server:latest
        cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest
    needs:
      - lint-and-build
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (From Cache)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: johnnyknighten/ark-sa-server:latest
        cache-from: type=gha

    - name: Set Execute Permission For All Test Scripts
      run: chmod -R +x ./tests/

    - name: Dependencies Tests
      run: |
        ./tests/dependencies.sh

    - name: Config File Generation Tests
      run: |
        ./tests/config_file_generation.sh

    - name: system-bootstrap Tests
      run: |
        ./tests/bin_scripts/system-bootstrap.sh

    - name: ark-sa-boostrap Tests
      run: |
        ./tests/bin_scripts/ark-sa-bootstrap.sh

    - name: ark-sa-updater Tests
      run: |
        ./tests/bin_scripts/ark-sa-updater.sh

    - name: ark-sa-server Tests
      run: |
        ./tests/bin_scripts/ark-sa-server.sh
